sudo: required
services:
  - docker

before_install:
  - docker build -t Visinho/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm test -- --coverage

after_success:
  - docker build -t Visinho/Complex-client ./client
  - docker build -t Visinho/Complex-nginx ./nginx
  - docker build -t Visinho/Complex-worker ./worker
  - docker build -t Visinho/Complex-server ./server

  # Login to Docker CLI
  - echo "$Docker_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push Visinho/Complex-client
  - docker push Visinho/Complex-nginx
  - docker push Visinho/Complex-worker
  - docker push Visinho/Complex-server